const fs = require('fs');
let file = fs.readFileSync('pages/DocumentVaultPage.tsx', 'utf-8');

file = file.replace(
  `                        {/* Status chip */}\n                        <span className={\`text-[9px] font-black px-2 py-0.5 rounded-lg border uppercase whitespace-nowrap \${\n                          doc.status === 'ACTIVE' ? 'bg-emerald-50 text-emerald-700 border-emerald-200' :\n                          doc.status === 'REPLIED' ? 'bg-blue-50 text-blue-700 border-blue-200' :\n                          doc.status === 'PENDING_ACTION' ? 'bg-amber-50 text-amber-700 border-amber-200 animate-pulse' :\n                          'bg-slate-50 text-slate-500 border-slate-200'\n                        }\`}>\n                          {doc.status.replace('_', ' ')}\n                        </span>`,
  `                        {/* Status chip */}\n                        <div className="flex flex-col items-end gap-1 shrink-0">\n                          <span className={\`text-[9px] font-black px-2 py-0.5 rounded-lg border uppercase whitespace-nowrap \${\n                            doc.status === 'ACTIVE' ? 'bg-emerald-50 text-emerald-700 border-emerald-200' :\n                            doc.status === 'REPLIED' ? 'bg-blue-50 text-blue-700 border-blue-200' :\n                            doc.status === 'PENDING_ACTION' ? 'bg-amber-50 text-amber-700 border-amber-200 animate-pulse' :\n                            'bg-slate-50 text-slate-500 border-slate-200'\n                          }\`}>\n                            {doc.status.replace('_', ' ')}\n                          </span>\n                          {isRetentionFlagged(doc) && (\n                            <span className="text-[8px] font-black px-2 py-0.5 rounded-lg border uppercase whitespace-nowrap bg-rose-50 text-rose-700 border-rose-200 animate-pulse flex items-center gap-1 shadow-sm">\n                              <Archive size={8} /> {retentionPolicy.action === 'ARCHIVE' ? 'Archival Due' : 'Purge Due'}\n                            </span>\n                          )}\n                        </div>`
);

fs.writeFileSync('pages/DocumentVaultPage.tsx', file);
